name: Setup Python with uv
description: Install uv, set up Python, and install dependencies

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.14"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        allow-prereleases: true

    - name: Install dependencies
      shell: bash
      run: uv sync --dev
